import { z } from 'zod';
import { readFileSync } from 'node:fs';
export const VERSION = JSON.parse(readFileSync(new URL('../../package.json', import.meta.url))).version;
export const CLIENT_VERSION = JSON.parse(readFileSync(new URL('../../anylist-js/package.json', import.meta.url))).version;
export const CLIENT_COMMIT = '1d3c9816c4ecfc3b2d8c5c48dd35619b125381c3';
export const CAPABILITY_VERSION = '1.0.0';
const text = z.string().max(12000);
const name = z.string().trim().min(1).max(512);
const id = z.string().min(1).max(128);
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v => !isNaN(Date.parse(v)) && new Date(v).toISOString().slice(0,10) === v, 'Invalid calendar date');
const opt = s => s.optional();
const selector = {name: opt(name), id: opt(id)};
const list = {list_name: opt(name), list_id: opt(id)};
const itemFields = {new_name: opt(name), quantity: opt(z.number().positive().max(1000000)), notes: opt(text), category: opt(name), categories: opt(z.record(name, name)), store_name: opt(z.string().max(512)), store_ids: opt(z.array(id).max(50)), manual_sort_index: opt(z.number().finite())};
const favoriteFields = {...itemFields}; delete favoriteFields.category; delete favoriteFields.categories;
const favoriteItem = {name,...favoriteFields}; delete favoriteItem.new_name;
const item = {name, ...itemFields}; delete item.new_name;
const ingredient = z.object({identifier: opt(id), name: opt(text), quantity: opt(text), rawIngredient: opt(text), note: opt(text), isHeading: opt(z.boolean())}).strict();
const recipe = {new_name: opt(name), ingredients: opt(z.array(ingredient).max(500)), steps: opt(z.array(text).max(500)), note: opt(text), source_name: opt(text), source_url: opt(z.string().max(2048)), prep_time: opt(z.number().int().min(0).max(100000)), cook_time: opt(z.number().int().min(0).max(100000)), servings: opt(text), rating: opt(z.number().int().min(0).max(5)), nutritional_info: opt(text), scale_factor: opt(z.number().positive().max(1000)), photo_ids: opt(z.array(id).max(100)), photo_urls: opt(z.array(z.string().url().max(2048)).max(100)), paprika_identifier: opt(text)};
const meal = {date: opt(date), title: opt(text), details: opt(text), recipe_id: opt(z.string().max(128)), recipe_name: opt(name), label_id: opt(z.string().max(128)), label_name: opt(name), recipe_scale_factor: opt(z.number().positive().max(1000)), order_added_sort_index: opt(z.number().finite())};
const definitions = [];
function add(tool, action, operationId, description, fields = {}, effect = 'read') {
  definitions.push({tool, action, operationId, description, effect, schema: z.object(fields).strict()});
}
add('shopping','list_lists','listShoppingLists','Discover shopping lists and canonical IDs.');
add('shopping','list_items','getShoppingList','Read a list and its items. Select an exact name or ID; include_checked defaults false.', {...list, include_checked:opt(z.boolean()), include_notes:opt(z.boolean()), category_set:opt(name)});
add('shopping','list_categories','listCategories','Read category sets and categories.',list);
add('shopping','list_stores','listStores','Read stores for a list.',list);
add('shopping','get_recents','listRecentItems','Read recently used items.',list);
add('shopping','get_favorites','listFavorites','Read favorite items.',list);
add('shopping','add_item','addShoppingItem','Add an item, or update/uncheck the uniquely matching existing item.', {...list,...item},'write');
add('shopping','add_items','addShoppingItems','Add up to 100 items in one call. Returns individual outcomes; partial writes are reported.', {...list, items:z.array(z.object(item).strict()).min(1).max(100)},'write');
add('shopping','update_item','updateShoppingItem','Update only supplied item fields.', {...list,...selector,...itemFields},'write');
add('shopping','set_item_store','setShoppingItemStore','Set store assignments; empty store_name clears assignments.', {...list,...selector,store_name:opt(z.string().max(512)),store_ids:opt(z.array(id).max(50))},'write');
for (const [action,operationId,desc,effect] of [['check_item','checkShoppingItem','Check one item.','write'],['uncheck_item','uncheckShoppingItem','Uncheck one item.','write'],['delete_item','deleteShoppingItem','Delete one explicitly selected item.','delete']]) add('shopping',action,operationId,desc,{...list,...selector},effect);
add('shopping','create_category','createCategory','Create a category in an existing category set.',{...list,name,category_set:opt(name)},'write');
add('shopping','rename_category','renameCategory','Rename one category.',{...list,name,new_name:name,category_set:opt(name)},'write');
add('shopping','delete_category','deleteCategory','Delete one category.',{...list,name,category_set:opt(name)},'delete');
add('shopping','add_favorite','addFavorite','Add a uniquely named favorite to the list existing favorites container.',{...list,...favoriteItem},'write');
add('shopping','update_favorite','updateFavorite','Update only supplied favorite fields.',{...list,...selector,...favoriteFields},'write');
add('shopping','remove_favorite','removeFavorite','Remove one favorite.',{...list,...selector},'delete');
add('recipes','list','listRecipes','Browse or search recipe summaries.',{search:opt(name),limit:opt(z.number().int().min(1).max(100)),offset:opt(z.number().int().min(0))});
add('recipes','get','getRecipe','Read complete supported recipe metadata.',selector);
add('recipes','create','createRecipe','Create a new recipe. Existing names are refused; use update.',{name,...recipe},'write');
add('recipes','update','updateRecipe','Update supplied fields while preserving unspecified recipe fields.',{...selector,...recipe},'write');
add('recipes','delete','deleteRecipe','Delete one explicitly selected recipe.',selector,'delete');
add('recipes','normalize','normalizeRecipe','Normalize raw text or a public HTTPS recipe URL. Optional save creates a recipe.',{url:opt(z.string().url().max(2048)),text:opt(z.string().min(1).max(100000)),save:opt(z.boolean())},'write');
add('recipes','import_url','importRecipe','Import and save a recipe from a public HTTPS URL.',{url:z.string().url().max(2048)},'write');
add('recipe_collections','list','listRecipeCollections','Read collections and their recipe IDs/names.');
add('recipe_collections','get','getRecipeCollection','Read a collection and recipe summaries.',selector);
add('recipe_collections','create','createRecipeCollection','Create a collection, optionally with existing recipes.',{name,recipe_names:opt(z.array(name).max(100))},'write');
add('recipe_collections','delete','deleteRecipeCollection','Delete one explicitly selected collection.',selector,'delete');
for (const [action,operationId,verb] of [['add_recipe','addRecipeToCollection','Add'],['remove_recipe','removeRecipeFromCollection','Remove']]) add('recipe_collections',action,operationId,`${verb} one recipe membership.`,{...selector,recipe_id:opt(id),recipe_name:opt(name)},'write');
add('meal_plan','list_events','getMealPlan','Read meal events using an exact date or inclusive date range.',{date:opt(date),start_date:opt(date),end_date:opt(date)});
add('meal_plan','list_labels','listMealLabels','Read meal labels and IDs.');
add('meal_plan','create_event','addMealPlanEvent','Create one dated meal, optionally linked to a recipe and label.',{...meal,date},'write');
add('meal_plan','update_event','updateMealPlanEvent','Update the details of one meal event. The pinned library does not persist date, title, label or recipe changes.',{details:text,event_id:id},'write');
add('meal_plan','delete_event','deleteMealPlanEvent','Delete one explicitly identified meal event.',{event_id:id},'delete');
add('service','status','getServiceStatus','Authenticate and report ready state, versions and last synchronization.');
add('service','capabilities','getCapabilities','Read the stable capability manifest.');
add('service','refresh','refreshAnyList','Refresh account data from the AnyList source of truth.');
export const CAPABILITIES = Object.freeze(definitions);
export function capability(tool,action) { return CAPABILITIES.find(x=>x.tool===tool && x.action===action); }
export function manifest() {return {version:CAPABILITY_VERSION,serverVersion:VERSION,clientVersion:CLIENT_VERSION,clientCommit:CLIENT_COMMIT,capabilities:CAPABILITIES.map(({schema,...rest})=>rest)};}
